# .streamlit/secrets.toml
SENDGRID_API_KEY = "SG.V......................................." # Paste your SendGrid API Key here
SENDER_EMAIL = "chrisamstore@gmail.com" # This MUST be the email you verified in SendGrid